name: "Test Python code"
on:
  push: # Only execute pipeline when someone pushes a commmit to these branches
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test: # Name of the job
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.13"]
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
      - name: Install dependencies
        run: |
          python -m pip install -r requirements.txt
      - name: Launch the unit test
        run: python -m pytest
