name: "Test Python code"
on:
  push: # Only execute pipeline when someone pushes a commmit to these branches
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test: # Name of the job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: "pip"
      - name: Install dependencies
        run: |
          python -m pip install -r requirements.txt
      - name: Launch the unit test
        run: pytest
